### PR TITLE
macosx appstore support

### PR DESCRIPTION
**Pull request by trevorlinton**
This adds a tool to sign node-webkit apps in preparation for the macosx app store.

### CODE REVIEW

**Comment by rborn** [comment]
+1 @gpetrov @quasado

**Comment by rogerwang** [comment]
This PR doesn't apply on nw13 architecture any more.

**Comment by gpetrov** [comment]
@rogerwang Does this means that the nw13 apps can now be submitted to the Mac Appstore and be able to function as fully sandboxed apps?

**Comment by rogerwang** [comment]
It simply means the PR is not valid any more and should be closed.

The issue for this is tracking with #4556

**Pull request closed without merging**
