### PR TITLE
Fix #4754: Correct encoding for clipboard.set()

### LINKED ISSUE #4754: [bug] clipboard.set does not work correctly with russian symbols
nw 0.13, 0.14, Windows 7
`var clipboard = gui.Clipboard.get();`
`clipboard.set('russian text', 'text')`
with nw 0.12 it works, but in new versions dont, it sets incorrect symbols

### PR DESCRIPTION
**Pull request by dr15x86**

### CODE REVIEW

**Comment by rogerwang** [comment]
Thanks :+1:

**Comment by rogerwang** [comment]
It didn't catch with our 0.14.2 build. Will release this fix with the next build.

**Comment by PavelSapachev** [comment]
> It didn't catch with our 0.14.2 build. Will release this fix with the next build.

This fix will be include into 0.14.3? When about to be released this build?

**Comment by rogerwang** [comment]
Chromium just released 50.0.2661.86. So we started the 0.14.2 release build on this version earlier today. This PR was submitted and merged after that.

It will be available in the next nightly build of 0.14 branch (which will happen 1-2 days later as we're in the middle of preparing 0.15 building slaves), and released in 0.14.3 in a week.

**Comment by PavelSapachev** [comment]
Thanks, Roger!

**Comment by rogerwang** [comment]
See the build here: http://dl.nwjs.io/live-build/04-25-2016/nw14-87ed72e-bf774e7-3d8c7fc-c56a187

**Pull request merged**
