### PR TITLE
Rename process.versions.node-webkit

### PR DESCRIPTION
**Pull request by adam-lynch**
From the console:

screen shot 2015-12-27 at 03 55 40

Is this alright? :smile:

Note: This PR is for the `nw13` branch.

### CODE REVIEW

**Comment by rogerwang** [comment]
Please see the rename here: https://github.com/nwjs/nw.js/blob/nw13/src/nw_content.cc#L447

We'll keep both 'node-webkit' and 'nwjs' for a while and then remove 'node-webkit'.

shell_content_renderer_client.cc is not used any more in nw13 and it'll be removed from the repo after 0.13 final release.

**Comment by adam-lynch** [comment]
@rogerwang Ok thanks :+1:

**Comment by rogerwang** [comment]
It will be renamed process.versions['nw'] in the upcoming beta release.

**Comment by adam-lynch** [comment]
@rogerwang I assume you mean `nwjs` like it is in the code you linked to above?

**Comment by rogerwang** [comment]
process.versions['nwjs'] will be renamed process.versions['nw'] in the upcoming beta release.

**Comment by adam-lynch** [comment]
Ok thanks @rogerwang. I ask because I just wrote https://github.com/Teamwork/node-auto-launch/blob/master/src/index.coffee#L21. I'll change that to use `process.versions.nwjs` only so (since the `process.versions.nw` was never released in a stable version)

**Comment by rogerwang** [comment]
process.versions.nw should be used.

**Comment by rogerwang** [comment]
see https://github.com/nwjs/nw.js/commit/a51cd87bbf159e9227d63b071e4e52866181dc25

**Comment by adam-lynch** [comment]
:+1:

**Pull request closed without merging**
