### PR TITLE
Remove TOC from homepage to avoid inconsistancy with navigation sidebar

### PR DESCRIPTION
**Pull request by ghostoy**
rework based on PR #5030

### CODE REVIEW

**Comment by ghostoy** [comment]
The origin author of PR #5030 didn't response for a long time. So here comes the patch based on his work and my comment.

**Comment by rogerwang** [comment]
Why did we add a TOC in the first place?

**Comment by ghostoy** [comment]
The original doc is designed to be similar to Node.js doc https://nodejs.org/api/. There are two TOCs on both left and right.

**Comment by rogerwang** [comment]
No, we needed the order to be right so we added a TOC.... Just removing it is not a solution.

**Comment by ghostoy** [comment]
@rogerwang Updated TOC to be consistent with navigation on the left.

**Pull request closed without merging**
