### PR TITLE
 Fix #8039; Grey default icon in taskbar on Windows

### LINKED ISSUE #8039: Custom icon in taskbar not showing with 0.73.0 - grey default icon only
The custom icon in the windows 11's taskbar is a grey default icon, with 0.73.0-sdk (or 'normal' non-sdk). It works flawlessly with 0.72.0 (and previous).

The odd thing with 0.73.0 is that the icon in the top-left corner (favico equivalent?) is there. The icon also is present in Task Manager (for the binary and all sub-processes spawned by nwjs too). And the icon also is fine with the Tray. But not on the main taskbar.

FYI: Disabling/enabling `nw2` doesnt change the icon issue. 

Attached: a printscreen of the nwjs icon (right) and the devtools icon (left). They used to both be my custom icon. 
WId9322LtC

- Operating System: Windows 11 x64
- NW.js Version: 0.73.0 (sdk/normal)
- Code snippet:
In `package.json` :
```json
  "window": {
    "width": 1024,
    "height": 654,
    "title": "My App",
    "icon": "foo/bar.png",
    "min_width": 885,
    "min_height": 518,
    "show": false
  },
```
in the js files after some background checks for the app to prepare to strat: 
```js
require('nw.gui').Window.get().show(true)
```

### PR DESCRIPTION
**Pull request by nhogle**
Fixes #8039

### CODE REVIEW

**Comment by nhogle** [comment]
@rogerwang : I'm also including a commit that deletes nw_content, since this got split into separate files [back in 2016](https://github.com/nwjs/nw.js/commit/7575e88522fa8e9b5643f55733539551bb0411aa).  It no longer makes sense to maintain the old code...  Thoughts?

**Comment by rogerwang** [comment]
Thanks. Could you remove the changes to nw_contents.* ? It's not related to the bug fix and I think they may be used somewhere.

**Comment by nhogle** [comment]
@rogerwang : Sure! I removed the commit that deletes the nw_content files.  This PR should now be ready to merge.
Thanks!

**Comment by sysrage** [comment]
@rogerwang please get this merged!

**Comment by benjismith** [comment]
@rogerwang I'd love to get this merged! I'm currently stuck using 0.72.0 until this bug gets fixed...

**Comment by benjismith** [comment]
Any news on this @rogerwang ?

**Review by rogerwang — APPROVED** [review]

**Pull request merged**
