### PR TITLE
Update Getting Started.md

### PR DESCRIPTION
**Pull request by ostwindli**

### CODE REVIEW

**Comment by ostwindli** [comment]
@rogerwang

**Comment by ayushmxn** [comment]
Maybe this can go in the wiki instead?

**Comment by ostwindli** [comment]
> Maybe this can go in the wiki instead?

ok. put it here: https://github.com/nwjs/nw.js/wiki/Getting-Started-with-nw.js

**Comment by ayushmxn** [comment]
Thanks!

**Pull request closed without merging**
