### PR TITLE
test: add crash-dump-report server demo of nodejs

### PR DESCRIPTION
**Pull request by ostli**

### CODE REVIEW

**Comment by ostwindli** [comment]
@rogerwang

**Comment by ayushmxn** [comment]
Is #7940 related to this?

**Comment by ostwindli** [comment]
> 

No, this is just an example of a nwjs-crash-report-server implemented in js

**Comment by ayushmxn** [comment]
@rogerwang based on what I can see in the diff, this would be a nice addition to the sanity tests

**Review by tharatau — COMMENTED** [review]
Hi @ostli, please disregard my earlier comment. I have now become more familiar with NW.js codebase. Sanity tests are automated via Chromedriver. If the test does not fit under sanity, I'd suggest adding it under manual.

**Pull request closed without merging**
