### PR TITLE
Fix #3143: remote debugging devtools page blank

### LINKED ISSUE #3143: Remote debugging/devtools page blank in v0.12
Starting nw with the `--remote-debugging-port` option does not work. nw listens on the port but does not return any data.

Starting nw: `nwjs-v0.12.0-rc1-linux-x64/nw --remote-debugging-port=9090`

Testing connection on this port:
```
$ telnet localhost 9090
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1

HTTP/1.1 200 OK
Content-Length:0
Content-Type:text/html; charset=UTF-8

```

I tested all v0.12.0 alphas and the rc1 release and all have the same issue on Linux x64. This issue is not present in v0.11.6.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9026713-remote-debugging-devtools-page-blank-in-v0-12?utm_campaign=plugin&utm_content=tracker%2F51989&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F51989&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wuyuehang**
ShellDevToolsDelegate::GetDiscoveryPageHTML should load resource bundle from
IDR_NW_DEVTOOLS_DISCOVERY_PAGE other than IDR_CONTENT_SHELL_DEVTOOLS_DISCOVERY_PAGE

### CODE REVIEW

**Comment by wuyuehang** [comment]
ping @polpo @rogerwang

**Comment by wuyuehang** [comment]
Also, the files "shell_devtools_delegate.cc/h" are duplicates of "shell_devtools_manager_delegate.cc/h" and aren't used in nw.gypi anymore. They  should be removed.

**Comment by rogerwang** [comment]
Thanks. Please submit another PR to add yourself to AUTHORS.

**Comment by wuyuehang** [comment]
Thanks @rogerwang

>>Also, the files "shell_devtools_delegate.cc/h" are duplicates of "shell_devtools_manager_delegate.cc/h" and aren't used in nw.gypi anymore. They should be removed.

Can I submit another PR to do those clean up?

**Comment by rogerwang** [comment]
No need to do it. The code will be dropped when I'm doing the refactoring
for NW13.

**Pull request merged**
