### PR TITLE
Adds the logic when removeAllListeners has no parameter

### LINKED ISSUE #5649: window.location.reload and .removeAllListeners(); do not remove event listeners
`window.location.reload` do not remove event listeners, after page reload listeners are registered twice. Calling `.removeAllListeners();` does not help either. Below example which illustrates problem. Press button and then close window. You will see message "We're closing..." twice in the console. I'm using Ubuntu 16.04 and nwjs 55.0.2883.87 

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using node.js <script>document.write(process.version)</script>.
    <input type="button" name="reload" value="reload" onclick="reload()" />

  </body>
  <script type="text/javascript" charset="utf-8">
var win = nw.Window.get();
function reload() {
	win.removeAllListeners();
	window.location.reload();
}
console.log = (msg) => {
	process.stdout.write(`${msg}\n`);
};
win.on('close', function() {
	this.hide(); // Pretend to be closed already
	console.log("We're closing...");
	this.close(true); // then close it forcely
});
  </script>
</html>
```

### PR DESCRIPTION
**Pull request by xzhan96**
fixed #5649

### CODE REVIEW

**Comment by xzhan96** [comment]
@rogerwang please help review, thanks.

**Comment by rogerwang** [comment]
Please change the documentation as well.

**Comment by xzhan96** [comment]
change the doc done, please review again.

**Comment by rogerwang** [comment]
You should add an entry like http://docs.nwjs.io/en/latest/References/Window/#winshowdevtoolsiframe-callback

**Comment by xzhan96** [comment]
ok, but I see the sequence is not alphabetical order, if any other rules to follow?

**Comment by xzhan96** [comment]
please review again

**Comment by xzhan96** [comment]
@rogerwang PTAL

**Pull request merged**
