### PR TITLE
Fix crash when using `additional_trust_anchors`

### PR DESCRIPTION
**Pull request by ghostoy**

### CODE REVIEW

**Comment by rogerwang** [comment]
Why it cannot be done in MainPartsPreCreateThreadsHook?

**Comment by ghostoy** [comment]
@rogerwang Because it will try to access io_thread, which at that time is not created yet.

**Comment by rogerwang** [comment]
Code style is incorrect in nw_content.cc

**Comment by ghostoy** [comment]
@rogerwang Fixed all issues based on latest code base. Please review.

**Pull request merged**
