### PR TITLE
[Screen Selection] OSX and Win implementation

### PR DESCRIPTION
**Pull request by jtg-gg**
Chrome Screen Selection does not work ubuntu linux
hence I am not yet supporting it on linux

how to use it:
var gui = require('nw.gui');
gui.Screen.Init();
gui.Screen.chooseDesktopMedia(["window","screen"], 
 function(streamId) {
  var vid_cons = {mandatory: {chromeMediaSource: 'desktop', chromeMediaSourceId: streamId, maxWidth: 1920, maxHeight: 1080}, optional:[]};
  navigator.webkitGetUserMedia({audio: false, video: vid_cons}, success_func, fallback_func);
});

### CODE REVIEW

**Comment by rogerwang** [comment]
@jtg-gg the buildbot fails : http://buildbot-master.node-webkit.org:8010/builders/mac32_nw12/builds/22/steps/ninja_release/logs/stdio

**Comment by jtg-gg** [comment]
@rogerwang is it only fail for mac_32 ?

**Comment by rogerwang** [comment]
@jtg-gg failed too for mac_64: http://buildbot-master.node-webkit.org:8010/builders/mac64_nw12/builds/23/steps/ninja_release/logs/stdio

windows and linux passed.

**Comment by jtg-gg** [comment]
@rogerwang can you force a clean build on OSX ?

**Comment by rogerwang** [comment]
thanks. it passed with a clean build.

**Comment by rogerwang** [comment]
I add some doc here, please revise it: https://github.com/nwjs/nw.js/wiki/Screen#choosedesktopmedia

**Pull request merged**
