### PR TITLE
Fix #2106: Updated Tray to use libappindicator in Linux

### LINKED ISSUE #2106: Minimize to tray not working in Ubuntu 14.4 Unity
The Code

screenshot from 2014-07-23 04 59 58

App Still Running in the System Monitor though as you can see the app shows that it is closed in the Launcher

screenshot from 2014-07-23 05 06 29

Nowhere to be found in the System Tray

screenshot from 2014-07-23 05 08 56

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3272718-minimize-to-tray-not-working-in-ubuntu-14-4-unity?utm_campaign=plugin&utm_content=tracker%2F51989&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F51989&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Elzair**
I updated the code in **src/api/tray/tray.h** and **src/api/tray/gray_gtk.cc** to use [libappindicator](https://launchpad.net/libappindicator). I made this change because I could not get my Tray menus to display in Ubuntu. The changes only apply to Linux and have been tested in Ubuntu 14.04 x86_64.

### CODE REVIEW

**Comment by polpo** [comment]
I like the idea of using libappindicator, but I am committed to keeping NW compiled and running on older distributions such as CentOS 6.6 which do not have that library available. A runtime test for libappindicator with fallback to gtk would be good, but if not feasible, a compile-time flag would be ok.

In any case I also wonder why Chromium's own support for this is not used.

**Comment by tommoor** [comment]
:+1: vote to get this fixed and merged, this is core functionality that has regressed. @polpo I think you're right that it should detect and fall back for other flavors of linux. 

@Elzair will you have chance to update this PR at this point or should someone else take it on?

**Comment by Elzair** [comment]
I cannot do it today, but I will try to do it within the week.

**Comment by Kloadut** [comment]
Any update on this?
It fixes a quite annoying bug.

@Elzair thank you for the work though :)

**Comment by remss** [comment]
+1
Tray does not work on recent Linux distribs :-(

**Comment by Elzair** [comment]
Okay, I need to allocate some time to fix this.

BTW, I am kind of embarassed at the dearth of git-fu in this pull request. Since this was initially proposed a while ago, would it be better to close this pull request and refresh my version of nw.js? So, are we all agreed that a runtime test for **libappindicator** is the way to go?

**Comment by polpo** [comment]
I think this may not be necessary any more. It looks like nw.js v0.12 uses `src/api/tray/tray_aura.cc` instead of `tray_gtk.cc`. That is, it is using Chromium's own tray API in its Aura toolkit. `tray_gtk.cc` is still in the source tree but it is not built.

I just did a simple test and my tray icon appears on Ubuntu 14.04 w/ Unity. I also tested my compile on CentOS 6.6 w/ Gnome 2 and it also works.

**Comment by remss** [comment]
I just try with Ubuntu 14.04 and nw 0.12 linux 64 and the tray does not appears.
Works fine on Windows7 + nw0.12

Here test test page ...

    <!DOCTYPE html>
    <html>
    <body>
    <script>
    var gui = require('nw.gui');
    var tray = new gui.Tray({ title: 'Tray !!!', icon: 'img/icon.png' });
    var menu = new gui.Menu();
    menu.append(new gui.MenuItem({ label: 'About me' }));
    tray.menu = menu;
    </script>
    </body>
    </html>

**Comment by Elzair** [comment]
Cool.

**Comment by polpo** [comment]
It looks like the Aura tray doesn't work 100% reliably. The first time I started an app it did not appear, but it appeared the second time and all times afterwards. Plus click events on the tray don't work very well: the user has to click on an empty menu item at the top of the dropdown to get the click event to trigger. I'm looking to see if this is a limitation of Aura's tray API or a bug.

**Comment by rogerwang** [comment]
This PR doesn't apply on nw13 architecture any more.

**Pull request closed without merging**
