### PR TITLE
support passing Buffer or ArrayBuffer to evalNWBin

### LINKED ISSUE #5220: Remote loading JS Bin Eval with evalNWBin()
Feature: Allow evalNWBin to load files remotely or through a variable.

This would be an excellent feature and addition to evalNWBin . 

A simplistic example.

```
var async_bin = $.ajax("/bins/file,bin")
evalNWBin(async_bin , frame)
```

https://github.com/nwjs/nw.js/issues/5168
@ghostoy

### PR DESCRIPTION
**Pull request by ghostoy**
fixed #5220

### CODE REVIEW

**Comment by VasiliyIsaichkin** [comment]
This thing is very necessary!

**Comment by ghostoy** [comment]
@rogerwang Could you please review and merge this PR?

**Comment by VasiliyIsaichkin** [comment]
@rogerwang please merge this PR :)

**Comment by gearintellix** [comment]
it was important for desktop app

**Comment by rogerwang** [comment]
merged in nw20.

**Pull request closed without merging**
