### PR TITLE
do not return invalid shortcuts for menu items

### LINKED ISSUE #5026: I can not remove shortcut key at menuItem
Hi everybody!

I have problem broken with menuItem at window XP. 

2016-06-24_08h43_57 

I can not remove it with shortcut key. What can help me at here?

Thanks all

### PR DESCRIPTION
**Pull request by ghostoy**
fixed #5026 

@rogerwang This is a patch for issues on NW14 for Win XP. If you think necessary for NW16, please merge this patch.

### CODE REVIEW

**Comment by rogerwang** [comment]
does it reproduce on other versions of Windows?

**Comment by ghostoy** [comment]
@rogerwang No. Only happens on XP.

**Comment by rogerwang** [comment]
Then why did you open this PR?

**Comment by ghostoy** [comment]
It doesn't bring any rendering issue with out the patch. But the logic here should prevent returning invalid shortcut.

**Pull request merged**
