### PR TITLE
Fixed devtools issue for nw12

### PR DESCRIPTION
**Pull request by ghostoy**
fixed rogerwang/node-webkit#2660
fixed rogerwang/node-webkit#2603

### CODE REVIEW

**Comment by watdafox** [comment]
if this works, please merge it :p

**Comment by MadLittleMods** [comment]
Any update? This is still an issue with v0.12.3

Here is the error thrown when trying to copy:
> Clipboard is not enabled in hosted mode. Please inspect using chrome://inspect

**Comment by rogerwang** [comment]
Since 0.13.0 will end beta soon, there is unlikely to be any 0.12 release any more.

**Comment by MadLittleMods** [comment]
@rogerwang Has it been fixed in 0.13.0? Good enough for me if that is the case.

**Comment by rogerwang** [comment]
@MadLittleMods 0.13.0 shouldn't have this issue. Though it's merged, there's still no release planned on 0.12.

**Pull request merged**
