### PR TITLE
Fix #916: support pac_url and auto proxy detection

### LINKED ISSUE #916: Adding an API to configure proxy [$85]
In 0.6.3 an API to get proxy for url has been added. Can we have an API to set proxy?

Chrome has a proxy API, which doesn't affect system settings. I'm wondering if nw could have the same feature.

http://developer.chrome.com/extensions/proxy.html

<bountysource-plugin>
---
There is a **[$85 open bounty](https://www.bountysource.com/issues/648111-adding-an-api-to-configure-proxy-85?utm_campaign=plugin&utm_content=tracker%2F51989&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F51989&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by fujunwei**
Add test cases for pac url.

(cherry picked from commit 206df0d26d089376d57b66590c7dfabb6e8babc3)

### CODE REVIEW

**Comment by fujunwei** [comment]
@rogerwang Passed test cases on Windows platform, PTAL. Thanks.

**Comment by fujunwei** [comment]
The PR of nw20 is  #5578

**Comment by fujunwei** [comment]
Yes, it's.

**Comment by rogerwang** [comment]
I'm doing the rebase from nw20 to nw21. Since the patch is already merged in nw20, it will be carried forward during my rebase. So this PR is not necessary. Thanks.

**Comment by fujunwei** [comment]
Got it. Thanks.

**Pull request closed without merging**
